name: Deploy Hugo Website to Plesk

on:
  push:
    branches:
      - master  # Der Workflow wird ausgelöst, wenn auf den Branch `master` gepusht wird

jobs:
  build-and-deploy:
    name: Build and Deploy Hugo Website
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout des Codes
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Installiere Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      # 3. Baue die Hugo-Website
      - name: Build Hugo Website
        run: hugo

      # 4. Deployment via SSH und SCP
      - name: Deploy to Server via SSH
        run: |
          echo "Adding SSH key"
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          echo "Deploying files via SCP"
          scp -r -o StrictHostKeyChecking=no ./public/* root@212.227.161.13:/var/www/vhosts/himmelsteil.com/httpdocs/
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSHE_KEY }}  # SSH-Schlüssel als GitHub Secret
